version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: thesocial-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword123
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - thesocial-network
    healthcheck:
      test: [ "CMD", "mongosh", "--username=superadmin", "--password=123456", "--eval", "db.adminCommand('ping')", "--authenticationDatabase=admin" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kafka:
    image: redpanda/redpanda:latest
    container_name: thesocial-redpanda
    ports:
      - "9092:9092"
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --advertise-kafka-addr 192.168.100.191:9092
    networks:
      - thesocial-network


volumes:
  mongodb_data:
  kafka_data:

networks:
  thesocial-network:
    driver: bridge
