import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#fff',
        borderBottomWidth: 0.5,
        borderBottomColor: '#e8e8e8',
    },
    backButton: {
        padding: 8,
        marginRight: 8,
    },
    searchContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        borderRadius: 24,
        paddingHorizontal: 12,
        height: 40,
        marginRight: 4,
        minWidth: 0,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: '#000',
        paddingVertical: 0,
        minWidth: 0,
    },
    clearButton: {
        padding: 4,
    },
    searchButton: {
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    searchButtonText: {
        color: '#FE2C55',
        fontSize: 14,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    content: {
        flex: 1,
        backgroundColor: '#fff',
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#fff',
    },
    suggestionIcon: {
        marginRight: 12,
    },
    suggestionContent: {
        flex: 1,
    },
    suggestionText: {
        fontSize: 16,
        color: '#000',
        fontWeight: '400',
    },
    suggestionHighlight: {
        color: '#FF0000',
        fontWeight: '400',
    },
    suggestionFooter: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        alignItems: 'center',
    },
    suggestionFooterText: {
        fontSize: 12,
        color: '#999',
        textAlign: 'center',
    },
    suggestionsLoadingContainer: {
        paddingVertical: 20,
        alignItems: 'center',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 100,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 14,
        color: '#666',
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 100,
        paddingHorizontal: 32,
    },
    errorText: {
        marginTop: 16,
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingTop: 100,
        paddingHorizontal: 32,
    },
    emptyText: {
        marginTop: 16,
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
    },
    searchResults: {
        flex: 1,
        backgroundColor: '#fff',
    },
    tabsContainer: {
        borderBottomWidth: 0.5,
        borderBottomColor: '#e5e5e5',
        backgroundColor: '#fff',
    },
    tabsContent: {
        paddingLeft: 20,
        paddingRight: 100,
        paddingVertical: 0,
    },
    tab: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginRight: 20,
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    tabActive: {
        borderBottomColor: '#000',
    },
    tabText: {
        fontSize: 15,
        color: '#666',
        fontWeight: '500',
        letterSpacing: -0.2,
        lineHeight: 32,
        includeFontPadding: true,
        flexShrink: 0,
    },
    tabTextActive: {
        color: '#000',
        fontWeight: '700',
    },
    usersSection: {
        paddingTop: 0,
        paddingBottom: 12,
        borderBottomWidth: 0.5,
        borderBottomColor: '#e8e8e8',
        backgroundColor: '#fff',
        width: '100%',
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingTop: 12,
        paddingBottom: 14,
        backgroundColor: '#fff',
        width: '100%',
    },
    sectionHeaderTitle: {
        fontSize: 21,
        fontWeight: '700',
        color: '#000',
        letterSpacing: -0.4,
        lineHeight: 28,
        textAlign: 'left',
    },
    seeAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    seeAllText: {
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
        letterSpacing: -0.1,
        marginRight: 2,
    },
    userResultItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 18,
        backgroundColor: '#fff',
        width: '100%',
    },
    userResultAvatar: {
        width: 68,
        height: 68,
        borderRadius: 34,
        marginRight: 18,
        backgroundColor: '#f5f5f5',
        borderWidth: 0.5,
        borderColor: '#e8e8e8',
    },
    userResultContent: {
        flex: 1,
        marginRight: 16,
        justifyContent: 'center',
        minWidth: 0,
    },
    userResultName: {
        fontSize: 17,
        fontWeight: '700',
        color: '#000',
        marginBottom: 4,
        letterSpacing: -0.3,
        lineHeight: 22,
    },
    userResultUsername: {
        fontSize: 15,
        color: '#666',
        marginBottom: 6,
        fontWeight: '400',
        letterSpacing: -0.2,
        lineHeight: 20,
    },
    userResultStats: {
        fontSize: 13,
        color: '#999',
        fontWeight: '400',
        letterSpacing: -0.1,
        lineHeight: 18,
    },
    followButton: {
        paddingHorizontal: 18,
        paddingVertical: 7,
        backgroundColor: '#FE2C55',
        borderRadius: 20,
        minWidth: 75,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#FE2C55',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    followButtonFollowed: {
        backgroundColor: '#f5f5f5',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        elevation: 2,
    },
    followButtonText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '700',
        letterSpacing: 0.2,
    },
    followButtonTextFollowed: {
        color: '#666',
    },
    loadMoreButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 18,
        marginHorizontal: 20,
        marginTop: 12,
        marginBottom: 8,
        borderTopWidth: 0.5,
        borderTopColor: '#f0f0f0',
    },
    loadMoreText: {
        fontSize: 15,
        color: '#FE2C55',
        fontWeight: '600',
        marginRight: 6,
    },
    postsSection: {
        paddingVertical: 24,
        paddingHorizontal: 3,
        backgroundColor: '#fafafa',
    },
    gridRow: {
        justifyContent: 'space-between',
        paddingHorizontal: 0,
    },
    gridItem: {
        backgroundColor: '#f8f8f8',
        borderRadius: 8,
        marginBottom: 6,
        marginHorizontal: 3,
        overflow: 'hidden',
        position: 'relative',
    },
    gridThumbnail: {
        width: '100%',
        height: '70%',
        resizeMode: 'cover',
    },
    gridThumbnailPlaceholder: {
        width: '100%',
        height: '70%',
        backgroundColor: '#f0f0f0',
        justifyContent: 'center',
        alignItems: 'center',
    },
    playButtonOverlay: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.6)',
        borderRadius: 12,
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    postIndicator: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(0,0,0,0.4)',
        borderRadius: 12,
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    multiImageIndicator: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: 'rgba(0,0,0,0.6)',
        borderRadius: 12,
        width: 24,
        height: 24,
        justifyContent: 'center',
        alignItems: 'center',
    },
    gridItemInfo: {
        padding: 8,
        height: '30%',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
    },
    gridItemTitle: {
        fontSize: 12,
        color: '#000',
        fontWeight: '400',
        lineHeight: 16,
        marginBottom: 4,
    },
    gridItemAuthorRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    authorInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        marginRight: 8,
    },
    gridItemAvatar: {
        width: 16,
        height: 16,
        borderRadius: 8,
        marginRight: 4,
    },
    gridItemAuthor: {
        fontSize: 10,
        color: '#666',
        flex: 1,
    },
    gridItemLikes: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    gridItemLikesText: {
        fontSize: 10,
        color: '#666',
        marginLeft: 2,
    },
    historySection: {
        padding: 16,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#000',
        marginBottom: 12,
    },
    historyList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
    },
    historyItemContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f5f5f5',
        borderRadius: 4,
        paddingHorizontal: 10,
        paddingVertical: 6,
        marginRight: 10,
        marginBottom: 10,
    },
    historyItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 8,
    },
    historyText: {
        marginLeft: 6,
        fontSize: 14,
        color: '#333',
    },
    recommendationSection: {
        padding: 16,
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    recommendationItem: {
        flexDirection: 'row',
        marginBottom: 16,
        alignItems: 'center',
    },
    recommendationThumbnail: {
        width: 60,
        height: 80,
        borderRadius: 4,
        backgroundColor: '#f0f0f0',
        marginRight: 12,
    },
    recommendationInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    recommendationTitle: {
        fontSize: 14,
        fontWeight: '500',
        color: '#000',
        marginBottom: 4,
        lineHeight: 18,
    },
    recommendationAuthor: {
        fontSize: 12,
        color: '#666',
    },
});

export default styles;