import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        justifyContent: "flex-end",
    },
    modalContainer: {
        backgroundColor: "#ffffff",
        height: height * 0.7,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: -5,
        },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 15,
        overflow: "hidden",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 8,
        marginBottom: 0,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0, 0, 0, 0.1)",
    },
    modalTitle: {
        color: "#000",
        fontSize: 15,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
        flex: 1,
        textAlign: "center",
    },
    dragHandle: {
        width: 50,
        height: 6,
        backgroundColor: "rgba(0, 0, 0, 0.3)",
        borderRadius: 3,
        alignSelf: "center",
        marginTop: 8,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 3,
    },
    closeButton: {
        padding: 6,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.05)",
    },
    sortButton: {
        padding: 6,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.05)",
        marginRight: 8,
    },
    headerSeparator: {
        height: 1,
        backgroundColor: "rgba(0, 0, 0, 0.1)",
        marginHorizontal: 16,
    },
    commentsList: {
        flex: 1,
        paddingHorizontal: 16,
    },
    commentsContainer: {
        paddingVertical: 10,
        paddingBottom: 20,
        flexGrow: 1,
    },
    commentItem: {
        flexDirection: "row",
        backgroundColor: "#fff",
        paddingHorizontal: 0,
        paddingVertical: 12,
        marginBottom: 0,
        borderRadius: 0,
        marginHorizontal: 0,
        minHeight: 80, // Fixed height for better performance
    },
    commentAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        marginRight: 12,
        borderWidth: 2,
        borderColor: "rgba(254, 44, 85, 0.3)",
        zIndex: 10,
        elevation: 10,
    },
    commentContent: {
        flex: 1,
    },
    commentHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    commentUsername: {
        color: "#000",
        fontSize: 14,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
        marginRight: 8,
    },
    commentTime: {
        color: "#666",
        fontSize: 12,
        fontFamily: "TikTokSans-Regular",
        marginRight: 16,
    },
    commentText: {
        color: "#000000",
        fontSize: 15,
        lineHeight: 22,
        fontFamily: "TikTokSans-Regular",
        marginBottom: 10,
        letterSpacing: 0.2,
    },
    commentActions: {
        flexDirection: "row",
        alignItems: "center",
    },
    likeButton: {
        flexDirection: "row",
        alignItems: "center",
        marginLeft: 16,
        paddingVertical: 2,
        paddingHorizontal: 4,
        zIndex: 10,
        elevation: 10,
    },
    likeCount: {
        color: "#999",
        fontSize: 12,
        marginLeft: 4,
        fontFamily: "TikTokSans-SemiBold",
        fontWeight: "600",
    },
    replyButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
    },
    inputContainer: {
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: "#ffffff",
    },
    inputWrapper: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f5f5f5",
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 8,
        minHeight: 40,
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.08)",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 3,
    },
    commentInput: {
        flex: 1,
        color: "#000",
        fontSize: 15,
        fontFamily: "TikTokSans-Regular",
        maxHeight: 80,
        textAlignVertical: "center",
        lineHeight: 18,
        paddingVertical: 0,
    },
    iconButton: {
        marginRight: 8,
        padding: 4,
        borderRadius: 14,
        backgroundColor: "rgba(0, 0, 0, 0.05)",
    },
    imageButton: {
        marginRight: 10,
        padding: 6,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.08)",
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.03)",
    },
    sendButton: {
        marginLeft: 10,
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 16,
        backgroundColor: "#FE2C55",
        shadowColor: "#FE2C55",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 3,
        minWidth: 56,
        alignItems: "center",
        justifyContent: "center",
    },
    sendButtonText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
        fontFamily: "TikTokSans-Bold",
        letterSpacing: 0.5,
    },
    replyButtonText: {
        color: "#666",
        fontSize: 12,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
    },
    emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 60,
        paddingHorizontal: 20,
    },
    emptyText: {
        color: "#000",
        fontSize: 18,
        fontWeight: "600",
        marginTop: 16,
        fontFamily: "TikTokSans-SemiBold",
    },
    emptySubText: {
        color: "#666",
        fontSize: 14,
        marginTop: 4,
        textAlign: "center",
        fontFamily: "TikTokSans-Regular",
    },
    emojiPicker: {
        backgroundColor: "#ffffff",
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: -2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    emojiList: {
        paddingHorizontal: 4,
    },
    emojiButton: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 22,
        backgroundColor: "rgba(0, 0, 0, 0.08)",
        marginHorizontal: 3,
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.03)",
    },
    emojiText: {
        fontSize: 22,
        textAlign: "center",
    },
    commentMeta: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 8,
        marginBottom: 4,
    },
    replyLink: {
        marginLeft: 16,
        paddingVertical: 2,
        zIndex: 10,
        elevation: 10,
    },
    replyLinkText: {
        color: "#666",
        fontSize: 12,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
    },
    viewRepliesButton: {
        marginTop: 8,
        paddingVertical: 4,
    },
    viewRepliesText: {
        color: "#666",
        fontSize: 12,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
    },
    addCommentSection: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: "rgba(255, 255, 255, 0.08)",
        backgroundColor: "rgba(0, 0, 0, 0.3)",
    },
    userAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        marginRight: 12,
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.1)",
    },
    addCommentText: {
        color: "#666",
        fontSize: 16,
        fontFamily: "TikTokSans-Regular",
    },
    dragIndicator: {
        width: 40,
        height: 4,
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        borderRadius: 2,
        alignSelf: "center",
        marginBottom: 8,
    },
    addCommentContent: {
        flexDirection: "row",
        alignItems: "center",
    },
});

export default styles;