import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        justifyContent: "flex-end",
        backgroundColor: 'transparent',
    },
    modalContainer: {
        backgroundColor: "#ffffff",
        height: height * 0.60,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 0,
        marginTop: -24,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: -5,
        },
        shadowOpacity: 0.3,
        shadowRadius: 15,
        elevation: 15,
        overflow: "hidden",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0, 0, 0, 0.08)",
    },
    filterButton: {
        padding: 6,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.05)",
    },
    searchTitleContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginHorizontal: 12,
    },
    searchLabel: {
        color: "#666",
        fontSize: 14,
        fontWeight: "400",
        fontFamily: "TikTokSans-Regular",
    },
    searchText: {
        color: "#4A9EFF",
        fontSize: 14,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
        flex: 1,
    },
    modalTitle: {
        color: "#000",
        fontSize: 15,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
        flex: 1,
        textAlign: "center",
    },
    dragHandle: {
        width: 50,
        height: 6,
        backgroundColor: "rgba(0, 0, 0, 0.3)",
        borderRadius: 3,
        alignSelf: "center",
        marginTop: 8,
        marginBottom: 16,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 3,
    },
    closeButton: {
        padding: 6,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.05)",
    },
    sortButton: {
        padding: 6,
        borderRadius: 16,
        backgroundColor: "rgba(0, 0, 0, 0.05)",
        marginRight: 8,
    },
    headerSeparator: {
        height: 1,
        backgroundColor: "rgba(0, 0, 0, 0.1)",
        marginHorizontal: 16,
    },
    commentsList: {
        flex: 1,
        paddingHorizontal: 16,
    },
    commentsContainer: {
        paddingVertical: 10,
        paddingBottom: 20,
        flexGrow: 1,
    },
    commentItem: {
        flexDirection: "row",
        backgroundColor: "#fff",
        paddingHorizontal: 0,
        paddingVertical: 16,
        marginBottom: 0,
        borderRadius: 0,
        marginHorizontal: 0,
        minHeight: 80,
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0, 0, 0, 0.05)",
    },
    commentAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 12,
    },
    initialAvatar: {
        backgroundColor: "#E5E7EB",
        justifyContent: "center",
        alignItems: "center",
    },
    initialAvatarText: {
        color: "#374151",
        fontSize: 18,
        fontWeight: "700",
    },
    commentContent: {
        flex: 1,
    },
    commentTopRow: {
        flexDirection: "row",
        flex: 1,
    },
    commentLeft: {
        flex: 1,
        marginRight: 12,
    },
    commentHeader: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    commentUsername: {
        color: "#000",
        fontSize: 15,
        fontWeight: "700",
        fontFamily: "TikTokSans-Bold",
        marginBottom: 4,
    },
    commentTime: {
        color: "#666",
        fontSize: 13,
        fontFamily: "TikTokSans-Regular",
    },
    commentText: {
        color: "#000000",
        fontSize: 15,
        lineHeight: 20,
        fontFamily: "TikTokSans-Regular",
        marginBottom: 8,
    },
    commentGifWrapper: {
        marginBottom: 8,
        borderRadius: 14,
        overflow: "hidden",
        backgroundColor: "#000",
        alignSelf: "flex-start",
    },
    commentGif: {
        width: width * 0.45,
        aspectRatio: 1,
    },
    commentMeta: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 4,
    },
    replyLink: {
        marginLeft: 12,
        paddingVertical: 2,
    },
    replyLinkText: {
        color: "#666",
        fontSize: 13,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
    },
    commentActions: {
        flexDirection: "row",
        alignItems: "center",
    },
    likeButton: {
        flexDirection: "row",
        alignItems: "center",
        marginLeft: 16,
        paddingVertical: 2,
        paddingHorizontal: 4,
    },
    likeCount: {
        fontSize: 11,
        marginLeft: 4,
        fontFamily: "TikTokSans-SemiBold",
        fontWeight: "600",
    },
    dislikeButton: {
        flexDirection: "row",
        alignItems: "center",
        marginLeft: 12,
        paddingVertical: 2,
        paddingHorizontal: 4,
    },
    replyButton: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 12,
        backgroundColor: "rgba(255, 255, 255, 0.05)",
    },
    inputContainer: {
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
        backgroundColor: "#ffffff",
    },
    inputRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    userAvatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        marginRight: 12,
    },
    inputWrapper: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f5f5f5",
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.08)",
    },
    commentInput: {
        flex: 1,
        color: "#000",
        fontSize: 13,
        fontFamily: "TikTokSans-Regular",
        paddingVertical: 0,
        marginRight: 8,
    },
    iconButton: {
        marginHorizontal: 4,
        padding: 2,
    },
    imageButton: {
        marginLeft: 4,
        padding: 2,
    },
    sendButton: {
        marginLeft: 12,
        padding: 8,
        borderRadius: 20,
        backgroundColor: "transparent",
        alignItems: "center",
        justifyContent: "center",
    },
    sendButtonText: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
        fontFamily: "TikTokSans-Bold",
        letterSpacing: 0.5,
    },
    replyButtonText: {
        color: "#666",
        fontSize: 12,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
    },
    emptyContainer: {
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 60,
        paddingHorizontal: 20,
    },
    emptyText: {
        color: "#000",
        fontSize: 18,
        fontWeight: "600",
        marginTop: 16,
        fontFamily: "TikTokSans-SemiBold",
    },
    emptySubText: {
        color: "#666",
        fontSize: 14,
        marginTop: 4,
        textAlign: "center",
        fontFamily: "TikTokSans-Regular",
    },
    emojiPicker: {
        backgroundColor: "#ffffff",
        paddingVertical: 16,
        paddingHorizontal: 16,
        borderTopWidth: 1,
        borderTopColor: "rgba(0, 0, 0, 0.08)",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: -2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 5,
    },
    emojiList: {
        paddingHorizontal: 4,
    },
    emojiButton: {
        paddingHorizontal: 12,
        paddingVertical: 10,
        borderRadius: 22,
        backgroundColor: "rgba(0, 0, 0, 0.08)",
        marginHorizontal: 3,
        borderWidth: 1,
        borderColor: "rgba(0, 0, 0, 0.03)",
    },
    emojiText: {
        fontSize: 22,
        textAlign: "center",
    },
    viewRepliesButton: {
        marginTop: 8,
        paddingVertical: 4,
        flexDirection: "row",
        alignItems: "center",
    },
    viewRepliesText: {
        color: "#666",
        fontSize: 13,
        fontWeight: "600",
        fontFamily: "TikTokSans-SemiBold",
    },
    addCommentSection: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderTopWidth: 1,
        borderTopColor: "rgba(255, 255, 255, 0.08)",
        backgroundColor: "rgba(0, 0, 0, 0.3)",
    },
    addCommentText: {
        color: "#666",
        fontSize: 16,
        fontFamily: "TikTokSans-Regular",
    },
    dragIndicator: {
        width: 40,
        height: 4,
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        borderRadius: 2,
        alignSelf: "center",
        marginBottom: 8,
    },
    addCommentContent: {
        flexDirection: "row",
        alignItems: "center",
    },
    repliesContainer: {
        marginTop: 12,
        marginLeft: 40, // Indent replies nhẹ
        paddingLeft: 0,
    },
    replyItem: {
        flexDirection: "row",
        paddingVertical: 12,
        paddingRight: 0,
    },
    replyAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        marginRight: 10,
    },
    replyContent: {
        flex: 1,
    },
    repliesLoading: {
        paddingVertical: 12,
        alignItems: "center",
    },
    replyingToContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        backgroundColor: "#f5f5f5",
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    replyingToText: {
        fontSize: 13,
        color: "#666",
        fontFamily: "TikTokSans-Regular",
    },
    replyingToUsername: {
        fontWeight: "600",
        color: "#FE2C55",
        fontFamily: "TikTokSans-SemiBold",
    },
    cancelReplyButton: {
        padding: 4,
    },
    replyBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 10,
        backgroundColor: '#F8F8F8',
        borderBottomWidth: 1,
        borderBottomColor: "rgba(0, 0, 0, 0.05)",
    },
    replyBarText: {
        fontSize: 13,
        color: '#666',
        fontFamily: "TikTokSans-Regular",
        flex: 1,
    },
    replyBarName: {
        fontWeight: '600',
        color: '#000',
        fontFamily: "TikTokSans-SemiBold",
    },
    closeReplyButton: {
        padding: 4,
        marginLeft: 8,
    },
});

export default styles;