spring:
  application:
    name: TheSocial
  data:
    mongodb:
      uri: ${MONGODB_URL}
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

server:
  port: 8081
  servlet:
    context-path: /api/v1
  cors: ${CORS_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_DURATION}
  refreshable: ${JWT_REFRESH_DURATION}

cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: ${CLOUD_NAME}



