spring:
  application:
    name: TheSocial
  data:
    mongodb:
      uri: ${MONGODB_URL}
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 2  0MB
      max-request-size: 50MB
      enabled: true
  kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.trusted.packages: "*"
server:
  port: 8082
  servlet:
    context-path: /api/v1
  cors: ${CORS_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_DURATION}
  refreshable: ${JWT_REFRESH_DURATION}

cloudinary:
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: ${CLOUD_NAME}


logging:
  level:
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.admin.AdminClient: ERROR


