spring:
  application:
    name: TheSocial
  data:
    mongodb:
      uri: ${MONGODB_URL}
      auto-index-creation: true

server:
  port: 8081
  servlet:
    context-path: /api/v1
  cors: ${CORS_URL}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_DURATION}
  refreshable: ${JWT_REFRESH_DURATION}




